name: ci/gh-actions/gui

on: [push, pull_request]

jobs:
  docker-windows-static:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: satackey/action-docker-layer-caching@v0.0.10
      if: "!startsWith(github.ref, 'refs/tags/v')"
      continue-on-error: true
      with:
        key: docker-windows-static-{hash}
        restore-keys: |
          docker-windows-static-
    - name: prepare build environment
      run: docker build --tag monero:build-env-windows --build-arg THREADS=3 --file Dockerfile.windows .
    - name: build
      run: docker run --rm -v /home/runner/work/monero-gui/monero-gui:/monero-gui -w /monero-gui monero:build-env-windows sh -c 'make depends root=/depends target=x86_64-w64-mingw32 tag=win-x64 -j3'
    - name: sha256sum
      run: shasum -a256 /home/runner/work/monero-gui/monero-gui/build/x86_64-w64-mingw32/release/bin/monero-wallet-gui.exe
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}
        path: |
          /home/runner/work/monero-gui/monero-gui/build/x86_64-w64-mingw32/release/bin/monero-wallet-gui.exe
          /home/runner/work/monero-gui/monero-gui/build/x86_64-w64-mingw32/release/bin/monerod.exe
